### ISSUE TITLE
Mobile: Can't scroll on landing page

### ISSUE THREAD

**Issue by retotrinkler** [melonport/website#10]
using moto g5 mobile phone, can't scroll down on landing page to see remainder of the page

**Comment by peterdraw** [comment]
Hi @retotrinkler could you test again using moto g5? it works on iphone 7.

**Comment by retotrinkler** [comment]
works pretty good

on team page, under advisers not all text is readable - might be bec they are displayed next to each other instead of below each other

**Comment by peterdraw** [comment]
Thanks!
The team page (advisors) has been fixed.
